name: Package aar file
on:
  workflow_dispatch:
    branches:
      - main

env:
  USER_NAME: ${{ secrets.USER_NAME }}

jobs:
  build-and-publish:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3
      - name: Set up JDK
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          server-id: github
          java-version: '17'
          settings-path: ${{ github.workspace }}
      - name: Clean the project
        run: ./gradlew clean
      - name: Build
        run: ./gradlew build release
      - name: Publish the library
        run: ./gradlew publish release -P USER_NAME=$USER_NAME -P TOKEN=${{ secrets.GITHUB_TOKEN }}
