name: Create Release
on:
  workflow_dispatch:
    branches:
      - main

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Set up JDK 11
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          server-id: github
          java-version: '11'
          settings-path: ${{ github.workspace }}
      - name: Create Release
        uses: actions/create-release@v1
        id: create_release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ vars.LIB_VERSION }}
          release_name: Release ${{ vars.LIB_VERSION }}
          body: ${{vars.RELEASE_MESSAGE}}
          draft: false
          prerelease: false
      - name: Get the Release ID
        run: echo "Release ID - ${{ steps.create_release.outputs.id }}"